'use client'
import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import AppHeader from '@/components/app.header';
import AppFooter from '@/components/app.footer';
import styles from '@/styles/layout.module.scss';
import MenuCategories from '@/components/app.menu';

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <AppHeader />
        </div>
        <div>
          <MenuCategories />
        </div>
        <div className={styles.layout}>
          <div style={{ background: 'rgb(241, 236, 236, 0.1)' }}>{children}</div>
        </div>
        <div><AppFooter /></div>

      </body>
    </html>
  )
}
